package com.admin4j.common.core.utils;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;

/**
 * @author andanyang
 * @since 2021/9/4 17:16
 */
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class CountryUtil {

    /**
     * 将国家的三字码转成二字码
     *
     * @param threeCode
     * @return
     */
    public static String getTwoCode(String threeCode) {
        if (threeCode.length() == 3) {
            switch (threeCode) {
                case "AND":
                    return "AD";//安道尔
                case "ARE":
                    return "AE";//阿拉伯联合酋长国
                case "AFG":
                    return "AF";//阿富汗
                case "ATG":
                    return "AG";//安提瓜和巴布达
                case "AIA":
                    return "AI";//安圭拉
                case "ALB":
                    return "AL";//阿尔巴尼亚
                case "ARM":
                    return "AM";//亚美尼亚
                case "ANT":
                    return "AN";//荷属安的列斯群岛
                case "AGO":
                    return "AO";//安哥拉
                case "ATA":
                    return "AQ";//南极洲
                case "ARG":
                    return "AR";//阿根廷
                case "ASM":
                    return "AS";//东萨摩亚
                case "AUT":
                    return "AT";//奥地利
                case "AUS":
                    return "AU";//澳大利亚
                case "ABW":
                    return "AW";//阿鲁巴
                case "ALA":
                    return "AX";//奥兰群岛
                case "AZE":
                    return "AZ";//阿塞拜疆
                case "BIH":
                    return "BA";//波斯尼亚和黑山共和国
                case "BRB":
                    return "BB";//巴巴多斯
                case "BGD":
                    return "BD";//孟加拉
                case "BEL":
                    return "BE";//比利时
                case "BFA":
                    return "BF";//布基纳法索
                case "BGR":
                    return "BG";//保加利亚
                case "BHR":
                    return "BH";//巴林
                case "BDI":
                    return "BI";//布隆迪
                case "BEN":
                    return "BJ";//贝宁
                case "BLM":
                    return "BL";//圣巴泰勒米岛
                case "BMU":
                    return "BM";//百慕大
                case "BRN":
                    return "BN";//文莱
                case "BOL":
                    return "BO";//玻利维亚
                case "BES":
                    return "BQ";//博奈尔岛, 圣尤斯特歇斯岛和萨巴岛
                case "BRA":
                    return "BR";//巴西
                case "BHS":
                    return "BS";//巴哈马
                case "BTN":
                    return "BT";//不丹
                case "BVT":
                    return "BV";//布韦岛
                case "BWA":
                    return "BW";//博茨瓦纳
                case "BLR":
                    return "BY";//白俄罗斯
                case "BLZ":
                    return "BZ";//伯里兹
                case "CAN":
                    return "CA";//加拿大
                case "CCK":
                    return "CC";//科库斯群岛
                case "COD":
                    return "CD";//刚果民主共和国
                case "CAF":
                    return "CF";//中非共和国
                case "COG":
                    return "CG";//刚果
                case "CHE":
                    return "CH";//瑞士
                case "CIV":
                    return "CI";//象牙海岸
                case "COK":
                    return "CK";//库克群岛
                case "CHL":
                    return "CL";//智利
                case "CMR":
                    return "CM";//喀麦隆
                case "CHN":
                    return "CN";//中国
                case "COL":
                    return "CO";//哥伦比亚
                case "CRI":
                    return "CR";//哥斯达黎加
                case "CUB":
                    return "CU";//古巴
                case "CPV":
                    return "CV";//佛得角
                case "CUW":
                    return "CW";//库拉索岛
                case "CXR":
                    return "CX";//圣诞岛
                case "CYP":
                    return "CY";//塞浦路斯
                case "CZE":
                    return "CZ";//捷克共和国
                case "DEU":
                    return "DE";//德国
                case "DJI":
                    return "DJ";//吉布提
                case "DNK":
                    return "DK";//丹麦
                case "DMA":
                    return "DM";//多米尼加联邦
                case "DOM":
                    return "DO";//多米尼加共和国
                case "DZA":
                    return "DZ";//阿尔及利亚
                case "ECU":
                    return "EC";//厄瓜多尔
                case "EST":
                    return "EE";//爱沙尼亚
                case "EGY":
                    return "EG";//埃及
                case "ESH":
                    return "EH";//西撒哈拉
                case "ERI":
                    return "ER";//厄里特尼亚
                case "ESP":
                    return "ES";//西班牙
                case "ETH":
                    return "ET";//埃塞俄比亚
                case "FIN":
                    return "FI";//芬兰
                case "FJI":
                    return "FJ";//斐济
                case "FLK":
                    return "FK";//富克兰群岛
                case "FSM":
                    return "FM";//密克罗尼西亚
                case "FRO":
                    return "FO";//法罗群岛
                case "FRA":
                    return "FR";//法国
                case "GAB":
                    return "GA";//加蓬
                case "GBR":
                    return "GB";//英国
                case "GRD":
                    return "GD";//格林纳达
                case "GEO":
                    return "GE";//格鲁吉亚
                case "GUF":
                    return "GF";//法属圭亚那
                case "GGY":
                    return "GG";//格恩西岛
                case "GHA":
                    return "GH";//加纳
                case "GIB":
                    return "GI";//直布罗陀
                case "GRL":
                    return "GL";//格陵兰
                case "GMB":
                    return "GM";//冈比亚
                case "GIN":
                    return "GN";//几内亚
                case "GLP":
                    return "GP";//瓜德罗普岛
                case "GNQ":
                    return "GQ";//赤道几内亚
                case "GRC":
                    return "GR";//希腊
                case "SGS":
                    return "GS";//南乔治亚岛和南桑德韦奇岛
                case "GTM":
                    return "GT";//危地马拉
                case "GUM":
                    return "GU";//关岛
                case "GNB":
                    return "GW";//几内亚比绍共和国
                case "GUY":
                    return "GY";//圭亚那
                case "HKG":
                    return "HK";//香港
                case "HMD":
                    return "HM";//赫德和麦克唐纳群岛
                case "HND":
                    return "HN";//洪都拉斯
                case "HRV":
                    return "HR";//克罗地亚
                case "HTI":
                    return "HT";//海地
                case "HUN":
                    return "HU";//匈牙利
                case "IDN":
                    return "ID";//印度尼西亚
                case "IRL":
                    return "IE";//爱尔兰
                case "ISR":
                    return "IL";//以色列
                case "IMN":
                    return "IM";//曼岛
                case "IND":
                    return "IN";//印度
                case "IOT":
                    return "IO";//英属印度洋领地
                case "IRQ":
                    return "IQ";//伊拉克
                case "IRN":
                    return "IR";//伊朗
                case "ISL":
                    return "IS";//冰岛
                case "ITA":
                    return "IT";//意大利
                case "JEY":
                    return "JE";//泽西岛
                case "JAM":
                    return "JM";//牙买加
                case "JOR":
                    return "JO";//约旦
                case "JPN":
                    return "JP";//日本
                case "KEN":
                    return "KE";//肯尼亚
                case "KGZ":
                    return "KG";//吉尔吉克斯坦
                case "KHM":
                    return "KH";//柬埔寨
                case "KIR":
                    return "KI";//基里巴斯
                case "COM":
                    return "KM";//科摩罗
                case "KNA":
                    return "KN";//圣基茨和尼维斯
                case "PRK":
                    return "KP";//朝鲜
                case "KOR":
                    return "KR";//韩国
                case "KWT":
                    return "KW";//科威特
                case "CYM":
                    return "KY";//开曼群岛
                case "KAZ":
                    return "KZ";//哈萨克斯坦
                case "LAO":
                    return "LA";//老挝
                case "LBN":
                    return "LB";//黎巴嫩
                case "LCA":
                    return "LC";//圣卢西亚
                case "LIE":
                    return "LI";//列支敦士登
                case "LKA":
                    return "LK";//斯里兰卡
                case "LBR":
                    return "LR";//利比里亚
                case "LSO":
                    return "LS";//莱索托
                case "LTU":
                    return "LT";//立陶宛
                case "LUX":
                    return "LU";//卢森堡
                case "LVA":
                    return "LV";//拉脱维亚
                case "LBY":
                    return "LY";//利比亚
                case "MAR":
                    return "MA";//摩洛哥
                case "MCO":
                    return "MC";//摩纳哥
                case "MDA":
                    return "MD";//摩尔多瓦
                case "MNE":
                    return "ME";//黑山
                case "MAF":
                    return "MF";//圣马丁
                case "MDG":
                    return "MG";//马达加斯加
                case "MHL":
                    return "MH";//马绍尔群岛
                case "MKD":
                    return "MK";//马其顿王国
                case "MLI":
                    return "ML";//马里
                case "MMR":
                    return "MM";//缅甸
                case "MNG":
                    return "MN";//蒙古
                case "MAC":
                    return "MO";//澳门特区
                case "MNP":
                    return "MP";//美属北马里亚纳群岛
                case "MTQ":
                    return "MQ";//马提尼克岛
                case "MRT":
                    return "MR";//毛里塔尼亚
                case "MSR":
                    return "MS";//蒙特塞拉群岛
                case "MLT":
                    return "MT";//马耳他
                case "MUS":
                    return "MU";//毛里求斯
                case "MDV":
                    return "MV";//马尔代夫
                case "MWI":
                    return "MW";//马拉维
                case "MEX":
                    return "MX";//墨西哥
                case "MYS":
                    return "MY";//马来西亚
                case "MOZ":
                    return "MZ";//莫桑比克
                case "NAM":
                    return "NA";//纳米比亚
                case "NCL":
                    return "NC";//新克里多尼亚群岛
                case "NER":
                    return "NE";//尼日尔
                case "NFK":
                    return "NF";//诺福克岛
                case "NGA":
                    return "NG";//尼日利亚
                case "NIC":
                    return "NI";//尼加拉瓜
                case "NLD":
                    return "NL";//荷兰
                case "NOR":
                    return "NO";//挪威
                case "NPL":
                    return "NP";//尼泊尔
                case "NRU":
                    return "NR";//瑙鲁
                case "NIU":
                    return "NU";//纽埃岛
                case "NZL":
                    return "NZ";//新西兰
                case "OMN":
                    return "OM";//阿曼
                case "PAN":
                    return "PA";//巴拿马
                case "PER":
                    return "PE";//秘鲁
                case "PYF":
                    return "PF";//法属玻利尼西亚
                case "PNG":
                    return "PG";//巴布亚新几内亚
                case "PHL":
                    return "PH";//菲律宾
                case "PAK":
                    return "PK";//巴基斯坦
                case "POL":
                    return "PL";//波兰
                case "SPM":
                    return "PM";//圣皮埃尔和密克隆群岛
                case "PCN":
                    return "PN";//皮特克恩岛
                case "PRI":
                    return "PR";//波多黎哥
                case "PSE":
                    return "PS";//巴勒斯坦
                case "PRT":
                    return "PT";//葡萄牙
                case "PLW":
                    return "PW";//帕劳
                case "PRY":
                    return "PY";//巴拉圭
                case "QAT":
                    return "QA";//卡塔尔
                case "REU":
                    return "RE";//留尼汪岛
                case "ROU":
                    return "RO";//罗马尼亚
                case "SRB":
                    return "RS";//塞尔维亚
                case "RUS":
                    return "RU";//俄罗斯
                case "RWA":
                    return "RW";//卢旺达
                case "SAU":
                    return "SA";//沙特阿拉伯
                case "SLB":
                    return "SB";//所罗门群岛
                case "SYC":
                    return "SC";//塞舌尔群岛
                case "SDN":
                    return "SD";//苏丹
                case "SWE":
                    return "SE";//瑞典
                case "SGP":
                    return "SG";//新加坡
                case "SHN":
                    return "SH";//圣赫勒拿岛
                case "SVN":
                    return "SI";//斯洛文尼亚
                case "SJM":
                    return "SJ";//斯瓦尔巴特和扬马延岛
                case "SVK":
                    return "SK";//斯洛伐克
                case "SLE":
                    return "SL";//塞拉里昂
                case "SMR":
                    return "SM";//圣马力诺
                case "SEN":
                    return "SN";//塞内加尔
                case "SOM":
                    return "SO";//索马里
                case "SUR":
                    return "SR";//苏里南
                case "SSD":
                    return "SS";//南苏丹
                case "STP":
                    return "ST";//圣多美和普林西比
                case "SLV":
                    return "SV";//萨尔瓦多
                case "SXM":
                    return "SX";//荷属圣马丁岛
                case "SYR":
                    return "SY";//叙利亚
                case "SWZ":
                    return "SZ";//斯威士兰
                case "TCA":
                    return "TC";//特克斯群岛和凯科斯群岛
                case "TCD":
                    return "TD";//乍得
                case "ATF":
                    return "TF";//法属南特立尼达
                case "TGO":
                    return "TG";//多哥
                case "THA":
                    return "TH";//泰国
                case "TJK":
                    return "TJ";//塔吉克斯坦
                case "TKL":
                    return "TK";//联合群岛
                case "TLS":
                    return "TL";//东帝汶
                case "TKM":
                    return "TM";//土库曼斯坦
                case "TUN":
                    return "TN";//突尼斯
                case "TON":
                    return "TO";//汤加
                case "TUR":
                    return "TR";//土耳其
                case "TTO":
                    return "TT";//特立尼达和多巴哥
                case "TUV":
                    return "TV";//图瓦卢
                case "TWN":
                    return "TW";//台湾地区
                case "TZA":
                    return "TZ";//坦桑尼亚
                case "UKR":
                    return "UA";//乌克兰
                case "UGA":
                    return "UG";//乌干达
                case "UMI":
                    return "UM";//美属小奥特兰群岛
                case "USA":
                    return "US";//美国
                case "URY":
                    return "UY";//乌拉圭
                case "UZB":
                    return "UZ";//乌兹别克斯坦
                case "VAT":
                    return "VA";//梵蒂冈
                case "VCT":
                    return "VC";//圣文森特和格林纳丁斯
                case "VEN":
                    return "VE";//委内瑞拉
                case "VGB":
                    return "VG";//英属维京群岛
                case "VIR":
                    return "VI";//美属维京群岛
                case "VNM":
                    return "VN";//越南
                case "VUT":
                    return "VU";//瓦努阿图
                case "WLF":
                    return "WF";//瓦利斯群岛和富图纳群岛
                case "WSM":
                    return "WS";//东萨摩亚
                case "YEM":
                    return "YE";//也门
                case "MYT":
                    return "YT";//马约特岛
                case "ZAF":
                    return "ZA";//南非
                case "ZMB":
                    return "ZM";//赞比亚
                case "ZWE":
                    return "ZW";//津巴布韦
                default:
                    return null;
            }
        } else {
            return threeCode;
        }
    }
}
